project_id = "ektodtogznnlwvcsawgu"

[functions.verify-checkout]
verify_jwt = false

[auth.email]
# Sender name and email
[auth.email.template.confirmation]
subject = "Confirme seu e-mail - PreciBake"
content_path = "./supabase/templates/confirmation.html"

[auth.email.template.recovery]
subject = "Redefinir sua senha - PreciBake"
content_path = "./supabase/templates/recovery.html"

[auth.email.template.email_change]
subject = "Confirme a alteração de e-mail - PreciBake"
content_path = "./supabase/templates/email_change.html"
